// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbqslesarohlkuubchpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicXNsZXNhcm9obGt1dWJjaHBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3Mjk5NTgsImV4cCI6MjA3MTMwNTk1OH0.kCTUF6xP5z4Hp-TgjbClCDlPiw8PnTk8vFWMVo30GpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});